```{r}
install.packages("dplyr")
library(dplyr) # Necesaria para usar la función glimpse(df)
```

```{r}
# Se lee un archivo csv y se guarda en el objeto df
df = (read.csv(file.choose(), header=T, encoding = "UTF-8"))

# Convierte las columnas de df en variables disponibles directamente en el entorno global.
# Permite referenciarlas sin necesidad de escribir df$nombre_columna.
attach(df)

# Resumen informativo de los datos - tendencias
#Genera un resumen estadístico informativo para cada columna del data frame df dependiendo de su tipo de dato.
summary(df)

# Muestra la estructura interna del objeto, revelando los tipos de cada columna y una vista resumida de los datos
str(df)

# Muestra una vista similar pero en un formato más compacto. Util cuando se trabaja con data frames grandes. 
glimpse(df)

# Consultar valores de columnas de interés con sumary()
summary(attack)
summary(defense)
summary(hp)
summary(weight_kg)
summary(height_m)

# Encuentre las cantidades de Pokémon por tipo:
table(type1)
table(type2)

```

```{r}
# Histograma más simple para la variable de hp
hist(hp)

#Histograma para hp un poco más elaborado
hist(hp, 
     main = "Distribución de variable hp", 
     xlab = "HP", 
     col = "lightblue", 
     border = "black")

# Histogramas para las columnas attack, defense, weight_kg y height_m.

hist(attack, 
  main = "Distribución de variable attack", 
  xlab = "Attack", 
  col = "lightgreen", 
  border = "black", 
  breaks = 15)

hist(defense,
  main = "Distribución de variable defense", 
  xlab = "Defense", 
  col = "lightyellow", 
  border = "black", 
  breaks = seq(min(defense), max(defense), by = 5),
  probability = TRUE)

hist(weight_kg,
     main = "Distribución de variable weight_kg",
     xlab = "Weight_kg",
     col = "lightpink",
     border = "black",
     xlim = c(0, 1000),
     ylim = c(0, 800))

hist(height_m,
     main = "Distribución de variable height_m",
     xlab = "height_m",
     col = "purple",
     border = "black",
     labels = TRUE,
     density = 25,
     angle = 45,)

```

```{r}
boxplot(attack ~ type1, 
        data=df, 
        main="Ataque por Tipo de Pokémon", 
        xlab="Tipo", 
        ylab="Ataque",
        las=2, 
        col="lightgreen")

boxplot(defense ~ type1, 
        data=df, 
        main="Defensa por Tipo de Pokémon", 
        xlab="Tipo", 
        ylab="Defensa",
        las=2, 
        col="gray",
        border = "blue")

boxplot(hp ~ generation, 
        data=df, 
        main="HP por Tipo de Generación", 
        xlab="Generación", 
        ylab="HP",
        las=2, 
        col="magenta",
        notch = TRUE)
```

```{r}

install.packages(c("dplyr",
    "ggplot2",
    "gridExtra",
    "tidyr",
    "reshape2",
    "RColorBrewer",
    "ggrepel"))

library(dplyr)
library(ggplot2)
library(gridExtra)
library(tidyr)
library(reshape2)
library(RColorBrewer)
library(ggrepel)

df = tibble::as_tibble(df)

colnames(df)[25] <- "classification"

df$capture_rate <- as.numeric(df$capture_rate)

head(df)

df = select(df, name, classification, hp, weight_kg,
height_m, speed, attack, defense,
sp_attack, sp_defense, type1, type2,
abilities, generation, is_legendary,
capture_rate)

head(df)

```

```{r}
density_hp <- ggplot(data=df, aes(hp)) + geom_density(col="white",fill="pink", alpha=0.8) +
ggtitle("Densidad de Hit Points o Vida")

density_speed <- ggplot(data=df, aes(speed)) + geom_density(col="white", fill="darkorchid", alpha=0.8) +
ggtitle("Densidad de velocidad")

density_attack <- ggplot(data=df, aes(attack)) + geom_density(col="white", fill="orange", alpha=0.7) +
ggtitle("Densidad caracteristicas ofensivas")

density_defense <- ggplot(data=df, aes(defense)) + geom_density(col="white", fill="firebrick", alpha=0.7) +
ggtitle("Densidad caracteristicas defensivas")

grid.arrange(density_hp, density_speed, density_attack, density_defense, ncol=2)

density_height_m <- ggplot(data=df, aes(height_m)) + geom_density(col="white", fill="lightgreen", alpha=0.7) +
ggtitle("Densidad caracteristicas de altura")

density_weight_kg <- ggplot(data=df, aes(defense)) + geom_density(col="white", fill="lightblue", alpha=0.7) +
ggtitle("Densidad caracteristicas de peso")

grid.arrange(density_hp, density_speed, density_attack, density_defense, density_height_m, density_weight_kg, ncol=3)
```

```{r}
ggplot(data=df, aes(type1)) +
  geom_bar(aes(fill=..count..), alpha=0.85) +
  scale_fill_gradient(low = "lightblue", high = "darkblue") + # Gradiente de colores
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("Distribucion basados en Tipo 1") +
  coord_flip()

ggplot(data=df, aes(type2)) +
  geom_bar(aes(fill=..count..), alpha=0.85) +
  scale_fill_gradient(low = "lightblue", high = "darkgreen") + # Gradiente de colores
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggtitle("Distribucion basados en Tipo 1") +
  coord_flip()

df %>%
  filter(is_legendary==1) %>%
  ggplot(aes(type1)) +
  geom_bar(aes(fill= ..count..)) +
  scale_fill_gradient(low = "lightblue", high = "darkblue") + # Gradiente de colores
  theme(axis.text.x = element_text(angle=90, hjust=0)) +
  ggtitle("Numero de Pokemon Legendarios del Type-1")

df %>%
  filter(is_legendary==0) %>%
  ggplot(aes(type1)) +
  geom_bar(aes(fill= ..count..)) +
  scale_fill_gradient(low = "orange", high = "red") + # Gradiente de colores
  theme(axis.text.x = element_text(angle=90, hjust=0)) +
  ggtitle("Numero de Pokemon Legendarios del Type-1")

```

```{r}
ggplot(data=df, aes(attack, defense)) + geom_point(aes(color=is_legendary), alpha=0.8) +
  scale_color_gradient(low="green", high="blue") + ggtitle("Contraste Defensa vs Ataque") +
  geom_label_repel(data=subset(df,attack > 150 | defense > 160 | attack < 25 | defense < 25),
  aes(label=name),
  box.padding = 0.35, point.padding = 0.5, size = 3,
  segment.color = 'grey50')

speed_attack_legendary <- ggplot(na.omit(df), aes(attack, speed)) +
  geom_point(aes(color=is_legendary)) +
  geom_label_repel(data=subset(df, (attack > 170 | speed > 150) & is_legendary == 1), aes(label=name),
  box.padding = 0.35, point.padding = 0.5, segment.color = 'grey50') +
  geom_smooth(method = "lm")
  print(speed_attack_legendary)
  
attack_weight_legendary <- ggplot(na.omit(df), aes(x = attack, y = weight_kg)) +
  geom_point(aes(color = factor(is_legendary)), size = 3, alpha = 0.7) +
  geom_label_repel(
    data = subset(df, (attack > 150 | weight_kg > 650) & is_legendary == 1),
    aes(label = name),
    box.padding = 0.35, point.padding = 0.5, segment.color = "grey50",
    size = 3
  ) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  labs(
    title = "Attack vs Weight (kg) - Pokémon Legendarios",
    x = "Attack",
    y = "Weight (kg)",
    color = "Legendario"
  ) +
  theme_minimal()
print(attack_weight_legendary)

attack_height_legendary <- ggplot(na.omit(df), aes(x = attack, y = height_m)) +
  geom_point(aes(color = factor(is_legendary)), size = 3, alpha = 0.7) +
  geom_label_repel(
    data = subset(df, (attack > 150 | height_m > 7.5) & is_legendary == 1),
    aes(label = name),
    box.padding = 0.35, point.padding = 0.5, segment.color = "grey50",
    size = 3
  ) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  labs(
    title = "Attack vs Height (m) - Pokémon Legendarios",
    x = "Attack",
    y = "Height (m)",
    color = "Legendario"
  ) +
  theme_minimal()
print(attack_height_legendary)

attack_hp_legendary <- ggplot(na.omit(df), aes(x = attack, y = hp)) +
  geom_point(aes(color = factor(is_legendary)), size = 3, alpha = 0.7) +
  geom_label_repel(
    data = subset(df, (attack > 170 | hp > 190) & is_legendary == 1),
    aes(label = name),
    box.padding = 0.35, point.padding = 0.5, segment.color = "grey50",
    size = 3
  ) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  labs(
    title = "Attack vs HP - Pokémon Legendarios",
    x = "Attack",
    y = "HP",
    color = "Legendario"
  ) +
  theme_minimal()
print(attack_hp_legendary)

```

```{r}
box_plot_attr <- select(df, type1, is_legendary, hp, defense, attack, sp_attack, sp_defense, speed)
box_plot_attr_leg <- filter(box_plot_attr, is_legendary == 1)
box_plot_attr_nor <- filter(box_plot_attr, is_legendary == 0)
box_plot_attr_leg_long <- gather(box_plot_attr_leg, attribute, value, -c(type1, is_legendary))
box_plot_attr_nor_long <- gather(box_plot_attr_nor, attribute, value, -c(type1, is_legendary))
bp_leg <- ggplot(data = box_plot_attr_leg_long, aes(attribute, value)) +
  geom_boxplot(fill="green4") +
  ggtitle("Pokemon Legendario")
bp_nor <- ggplot(data = box_plot_attr_nor_long, aes(attribute, value)) + geom_boxplot(fill =
"yellow2") + ggtitle("Pokemon No Legendario")
grid.arrange(bp_leg, bp_nor,ncol=2)
```

```{r}
hmap_attr <- select(df, type1, is_legendary, hp, defense, attack, sp_attack, sp_defense, speed)
hmap_attr_leg <- filter(hmap_attr, is_legendary == 1)
hmap_attr_leg <- group_by(hmap_attr_leg, type1)
hmap_attr_leg <- summarise(hmap_attr_leg, hp=median(hp), attack=median(attack),
defense=median(defense), sp_attack=median(sp_attack), sp_defense=median(sp_defense),
speed=median(speed))
hmap_attr_leg_m <- melt(hmap_attr_leg)
hm.palette <- colorRampPalette(rev(brewer.pal(5, 'RdYlBu')), space='Lab')
ggplot(data=hmap_attr_leg_m, aes(type1, variable)) + geom_tile(aes(fill=value)) + ggtitle("Pokémon
Legendaio: Type1 - Atributo") + scale_fill_gradientn(colours = hm.palette(100)) + theme(axis.text.x =
element_text(angle=90, hjust=0)) + coord_equal()

hmap_attr <- select(df, type1, is_legendary, hp, defense, attack, sp_attack, sp_defense, speed)
hmap_attr_non_leg <- filter(hmap_attr, is_legendary == 0)
hmap_attr_non_leg <- group_by(hmap_attr_non_leg, type1)
hmap_attr_non_leg <- summarise(hmap_attr_non_leg,
  hp = median(hp),
  attack = median(attack),
  defense = median(defense),
  sp_attack = median(sp_attack),
  sp_defense = median(sp_defense),
  speed = median(speed)
)
hmap_attr_non_leg_m <- melt(hmap_attr_non_leg)
hm.palette <- colorRampPalette(rev(brewer.pal(5, "RdYlBu")), space = "Lab")
ggplot(data = hmap_attr_non_leg_m, aes(x = type1, y = variable)) +
  geom_tile(aes(fill = value)) +
  ggtitle("Pokémon no legendarios: Tipo1 - Atributo") +
  scale_fill_gradientn(colours = hm.palette(100)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 0)) +
  coord_equal()

```

```{r}
hmap_attr <- select(df, type1, is_legendary, hp, defense, attack, sp_attack, sp_defense, speed)
hmap_attr_leg <- filter(hmap_attr, is_legendary == 1)
hmap_attr_leg <- group_by(hmap_attr_leg, type1)
hmap_attr_leg <- summarise(hmap_attr_leg, hp=median(hp), attack=median(attack),
defense=median(defense), sp_attack=median(sp_attack), sp_defense=median(sp_defense),
speed=median(speed))
row.names(hmap_attr_leg) <- hmap_attr_leg$type1
hmap_attr_leg$type1 <- NULL
hmap_attr_leg$is_legendary <- NULL
hmap_attr_leg_cor <- cor(hmap_attr_leg)
hmap_attr_leg_cor_m <- melt(hmap_attr_leg_cor)
hm.palette <- colorRampPalette(rev(brewer.pal(4, 'RdBu')), space='Lab')
11
ggplot(data=hmap_attr_leg_cor_m, aes(Var1, Var2)) + geom_tile(aes(fill=value)) + ggtitle("Correlación
de Atributos - Legendarios") + scale_fill_gradientn(colours = hm.palette(100)) + coord_equal()
```

```{r}
df= (read.csv(file.choose(), header=T, encoding = "UTF-8"))
attach(df)
df = tibble::as_tibble(df)
colnames(df)[25] <- "classification"
df$capture_rate <- as.numeric(df$capture_rate)
df_fight_against <- select(df, type1, against_bug:against_water)
head(df_fight_against)
df_fight_against_g <- group_by(df_fight_against, type1)
df_fight_against_summ <- summarise(df_fight_against_g,
against_bug = median(against_bug),
against_dark = median(against_dark),
against_dragon = median(against_dragon),
against_electric = median(against_electric),
against_fairy = median(against_fairy),
against_fight = median(against_fight),
against_fire = median(against_fire),
against_flying = median(against_flying),
against_ghost = median(against_ghost),
against_grass = median(against_grass),
against_ground = median(against_ground),
against_ice = median(against_ice),
against_normal = median(against_normal),
against_poison = median(against_poison),
against_psychic = median(against_psychic),
against_rock = median(against_rock),
against_steel = median(against_steel),
against_water = median(against_water))
# Construimos el heatmap
df_fight_against_long <- melt(df_fight_against_summ)
hm.palette <- colorRampPalette(rev(brewer.pal(9, 'RdYlBu')), space='Lab')
ggplot(data=df_fight_against_long, aes(type1, variable)) + geom_tile(aes(fill=value)) +
scale_fill_gradientn(colours = hm.palette(100)) + coord_equal() +
theme(axis.text.x=element_text(angle=90, hjust=0)) + ggtitle("Efectividad por tipo de Pokemon")
```

