```{r}
# Ejercicio

# Se quiere determinar si existen evidencias significativas de que la topología de red (variable 
# topología, con valores malla y estrella) afecta el tiempo de transferencia entre nodos

# NOTA: Para todo el ejercicio supondremos un nivel de significación de 0.05 (el Alpha!) 
```

```{r}
library(tidyverse)

redes = (read.csv(file.choose(), header=TRUE, encoding = "UTF-8"))
attach(redes)

head(redes, 10)
```

```{r}
# 1. Establecer la Hipótesis

# H0: no hay diferencia entre las medias poblacionales: μ(estrella) = μ(malla) 
# HA: si hay diferencia entre las medias poblacionales:  μ(estrella) ≠ μ(malla)

```

```{r}
# 2. Parámetro estimado (estadístico)

# Se calcula la diferencia entre las medias muestrales. Primero se crea top_est con los datos de 
# tiempos filtrados por la topología estrella, y luego top_malla para la topología de malla. Luego se 
# calcula la diferencia de las medias de ambas:

top_est <- redes %>% filter(topologia == "estrella") %>% pull(tiempo)
top_malla <- redes %>% filter(topologia == "malla") %>% pull(tiempo)

mean(top_malla) - mean(top_est)

# Hay una diferencia de 0.3419935 milisegundos entre ambas medias, pero todavía no sabemos si esta 
# diferencia es significativa o no.
```

```{r}
# 3. Validar las condiciones para aplicar una prueba T

# 3.1. Independencia:  
# Se trata de un muestreo aleatorio. Se puede afirmar que los eventos son independientes. Sin 
# embargo, podemos también realizar un gráfico de las observaciones respecto del tiempo en que 
# se tomaron:

if (length(dev.list()) > 1) dev.off()  # Cierra dispositivos gráficos activos si hay

plot(redes$tiempo, axes=TRUE, ylab = "Tiempo observado", xlab = "Observaciones")
abline(h = mean(redes$tiempo), col = "blue")

# Puede verse que no se observan patrones aparentes que comprometan la independencia de las 
# observaciones.
```

```{r}
# 3.2. Normalidad: 
# Se pueden crear histogramas para ver la forma de las observaciones.

ggplot(redes, aes(x = tiempo)) +  
  geom_histogram(aes(y = after_stat(density), colour = topologia)) + 
  facet_grid(.~ topologia) + 
  theme_bw() + theme(legend.position = "none") + 
  theme (text = element_text(size=16))

# Las formas de los histogramas no muestran claramente que las observaciones sigan una 
# distribución normal. En ambos casos parece que hay una asimetría hacia la izquierda. 
```

```{r}
# Otro gráfico que se puede utilizar es la gráfica de probabilidad normal (que en R puede hacerse 
# con qqnorm y qqline). Por un lado, qqnorm grafica las observaciones ordenadas de la muestra 
# contra sus respectivas frecuencias acumuladas, mientras que qqline muestra una línea de 
# referencia de cómo deberían alinearse los datos si siguen una distribución normal.

par(mfrow = c(1, 2)) 

qqnorm(top_malla, xlab = "", ylab = "", 
  main = "Topología malla", col = "firebrick")
qqline(top_malla) 

qqnorm(top_est, xlab = "", ylab = "", 
  main = "Topología estrella", col = "springgreen4") 
qqline(top_est)

# Este gráfico QQ compara los cuantiles de los datos observados con los cuantiles teóricos de la 
# distribución normal. Si los puntos del gráfico caen sobre la línea recta, los datos se distribuyen 
# aproximadamente de forma normal. En ambos casos, las observaciones más pequeñas no caen sobre 
# la línea teórica.
# En este caso no es claro que los datos sigan la distribución normal, ni para la topología de malla ni 
# para la de estrella.
```



